name: Build & Release Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: c0305/enkiflow
      IMAGE_TAG: ${{ github.event.pull_request.number && format('pr-{0}', github.event.pull_request.number) || 'latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        # Remember to create DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets in Settings → Secrets → Actions
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Composer image tag exists
        run: docker manifest inspect composer:2.8.9

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64

      - name: Verify Laravel Scout
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: |
          docker run --rm -e APP_ENV=testing -e SCOUT_DRIVER=database \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            php artisan scout:index --pretend

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          name: release-${{ github.sha }}
          body: |
            Docker image tag: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          files: docs/docker.md

