name: Build & Release Docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      IMAGE_NAME: c0305/enkiflow
      IMAGE_TAG: ${{ github.event.pull_request.number && format('pr-{0}', github.event.pull_request.number) || (startsWith(github.ref, 'refs/tags/v') && github.ref_name || 'latest') }}
      COMPOSER_CACHE_DIR: ~/.composer/cache
      NODE_CACHE_DIR: ~/.npm
      DOCKER_BUILD_ARGS: --memory=6g --cpu-quota=150000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache Composer dependencies
      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      # Cache NPM dependencies
      - name: Cache NPM packages
        uses: actions/cache@v4
        with:
          path: ${{ env.NODE_CACHE_DIR }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Build for multiple platforms
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          provenance: false
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.repository.updated_at }}

      - name: Verify Laravel Installation
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: |
          docker run --rm -e APP_ENV=testing \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            php artisan --version

      # Only create release on tags
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: |
            ## Docker Image
            
            ```bash
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ```
            
            ### Supported Platforms
            - linux/amd64
            - linux/arm64
            
            ### What's Changed
            See the full changelog below.
          files: docs/docker.md
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}